name: opencca-build

# CI Build script for tfa

on:
  push:
    branches: [opencca/main, opencca/systex25, opencca/next]
  workflow_dispatch:

concurrency:
  group: schedule-${{ github.workflow }}
  cancel-in-progress: true

env:
  CI_REPO: https://github.com/opencca/ci-scripts
  CI_RUN_SCRIPT: run-ci.sh
  CI_BUILD_SCRIPT: build-tfa.sh

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: true
          path: trusted-firmware-a

      - name: Clone and run CI
        run: |
          rm -r .ci || true
          git clone --depth 1 "$CI_REPO" .ci
          cd .ci
          ./"$CI_RUN_SCRIPT" "$GITHUB_WORKSPACE" ./"$CI_BUILD_SCRIPT"

      - name: Upload snapshot
        uses: actions/upload-artifact@v4
        with:
          name: tfa-snapshot
          path: snapshot/bl31.elf
          if-no-files-found: error
